DROP TABLE "ACCOUNT" CASCADE CONSTRAINTS;
DROP TABLE "ACTOR" CASCADE CONSTRAINTS;
DROP TABLE "EPISODE" CASCADE CONSTRAINTS;
DROP TABLE "GENRE" CASCADE CONSTRAINTS;
DROP TABLE "MOVIE" CASCADE CONSTRAINTS;
DROP TABLE "MOVIE_CAST_ACTOR" CASCADE CONSTRAINTS;
DROP TABLE "MOVIE_HAS_GENRE" CASCADE CONSTRAINTS;
DROP TABLE "RATING" CASCADE CONSTRAINTS;
DROP TABLE "VERSION" CASCADE CONSTRAINTS;
DROP TABLE "VIEWER_FAVORS_MOVIE" CASCADE CONSTRAINTS;
DROP TABLE "VIEWER_WATCH_MOVIE" CASCADE CONSTRAINTS;

-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   at:        2020-10-16 22:09:02 KST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ACCOUNT 
    ( 
     Email_id     VARCHAR2 (50 CHAR)  NOT NULL , 
     Password     VARCHAR2 (50 CHAR)  NOT NULL , 
     Phone_number VARCHAR2 (20 CHAR)  NOT NULL , 
     Name         VARCHAR2 (20 CHAR)  NOT NULL , 
     Address      VARCHAR2 (200) , 
     Gender       CHAR (1 CHAR) , 
     Birth_date   DATE , 
     Job          VARCHAR2 (20 CHAR) , 
     Membership   VARCHAR2 (20 CHAR) , 
     isAdmin      NUMBER 
    ) 
;

ALTER TABLE ACCOUNT 
    ADD CONSTRAINT ACCOUNT_PK PRIMARY KEY ( Email_id ) ;

CREATE TABLE ACTOR 
    ( 
     Actor_id VARCHAR2 (20 CHAR)  NOT NULL , 
     name     VARCHAR2 (20 CHAR) 
    ) 
;

ALTER TABLE ACTOR 
    ADD CONSTRAINT ACTOR_PK PRIMARY KEY ( Actor_id ) ;

CREATE TABLE EPISODE 
    ( 
     Title_id        VARCHAR2 (20 CHAR)  NOT NULL , 
     Parent_title_id VARCHAR2 (20 CHAR)  NOT NULL , 
     Season_number   NUMBER , 
     Episode_number  NUMBER 
    ) 
;

ALTER TABLE EPISODE 
    ADD CONSTRAINT EPISODE_PK PRIMARY KEY ( Parent_title_id, Title_id ) ;

CREATE TABLE GENRE 
    ( 
     Genre_id VARCHAR2 (20 CHAR)  NOT NULL , 
     Name     VARCHAR2 (20 CHAR) 
    ) 
;

ALTER TABLE GENRE 
    ADD CONSTRAINT GENRE_PK PRIMARY KEY ( Genre_id ) ;

CREATE TABLE MOVIE 
    ( 
     Title_id     VARCHAR2 (20 CHAR)  NOT NULL , 
     Type        VARCHAR2 (50 CHAR) , 
     Runtime      NUMBER , 
     Start_year   DATE , 
     Total_rating NUMBER , 
     Num_votes    NUMBER 
    ) 
;

ALTER TABLE MOVIE 
    ADD CONSTRAINT MOVIE_PK PRIMARY KEY ( Title_id ) ;

CREATE TABLE MOVIE_CAST_ACTOR 
    ( 
     MOVIE_Title_id VARCHAR2 (20 CHAR)  NOT NULL , 
     ACTOR_Actor_id VARCHAR2 (20 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE MOVIE_CAST_ACTOR 
    ADD CONSTRAINT MOVIE_CAST_ACTOR_PK PRIMARY KEY ( MOVIE_Title_id, ACTOR_Actor_id ) ;

CREATE TABLE MOVIE_HAS_GENRE 
    ( 
     MOVIE_Title_id VARCHAR2 (20 CHAR)  NOT NULL , 
     GENRE_Genre_id VARCHAR2 (20 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE MOVIE_HAS_GENRE 
    ADD CONSTRAINT MOVIE_HAS_GENRE_PK PRIMARY KEY ( MOVIE_Title_id, GENRE_Genre_id ) ;

CREATE TABLE RATING 
    ( 
     MOVIE_Title_id   VARCHAR2 (20 CHAR)  NOT NULL , 
     ACCOUNT_Email_id VARCHAR2 (50 CHAR)  NOT NULL , 
     Stars            NUMBER 
    ) 
;

ALTER TABLE RATING 
    ADD CONSTRAINT RATING_PK PRIMARY KEY ( ACCOUNT_Email_id, MOVIE_Title_id ) ;

CREATE TABLE VERSION 
    ( 
     MOVIE_Title_id VARCHAR2 (20 CHAR)  NOT NULL , 
     Ordering       NUMBER  NOT NULL , 
     Title          VARCHAR2 (200 CHAR) , 
     Region         VARCHAR2 (10 CHAR) , 
     Language       VARCHAR2 (20 CHAR) 
    ) 
;

ALTER TABLE VERSION 
    ADD CONSTRAINT VERSION_PK PRIMARY KEY ( Ordering, MOVIE_Title_id ) ;

CREATE TABLE VIEWER_FAVORS_MOVIE 
    ( 
     ACCOUNT_Email_id VARCHAR2 (50 CHAR)  NOT NULL , 
     MOVIE_Title_id   VARCHAR2 (20 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE VIEWER_FAVORS_MOVIE 
    ADD CONSTRAINT VIEWER_FAVORS_MOVIE_PK PRIMARY KEY ( ACCOUNT_Email_id, MOVIE_Title_id ) ;

CREATE TABLE VIEWER_WATCH_MOVIE 
    ( 
     ACCOUNT_Email_id  VARCHAR2 (50 CHAR)  NOT NULL , 
     MOVIE_Title_id    VARCHAR2 (20 CHAR)  NOT NULL , 
     Playback_position NUMBER 
    ) 
;

ALTER TABLE VIEWER_WATCH_MOVIE 
    ADD CONSTRAINT VIEWER_WATCH_MOVIE_PK PRIMARY KEY ( ACCOUNT_Email_id, MOVIE_Title_id ) ;

ALTER TABLE EPISODE 
    ADD CONSTRAINT EPISODE_MOVIE_FK FOREIGN KEY 
    ( 
     Title_id
    ) 
    REFERENCES MOVIE 
    ( 
     Title_id
    ) 
;

ALTER TABLE EPISODE 
    ADD CONSTRAINT EPISODE_MOVIE_FKv2 FOREIGN KEY 
    ( 
     Parent_title_id
    ) 
    REFERENCES MOVIE 
    ( 
     Title_id
    ) 
;

ALTER TABLE MOVIE_CAST_ACTOR 
    ADD CONSTRAINT MOVIE_CAST_ACTOR_ACTOR_FK FOREIGN KEY 
    ( 
     ACTOR_Actor_id
    ) 
    REFERENCES ACTOR 
    ( 
     Actor_id
    ) 
;

ALTER TABLE MOVIE_CAST_ACTOR 
    ADD CONSTRAINT MOVIE_CAST_ACTOR_MOVIE_FK FOREIGN KEY 
    ( 
     MOVIE_Title_id
    ) 
    REFERENCES MOVIE 
    ( 
     Title_id
    ) 
;

ALTER TABLE MOVIE_HAS_GENRE 
    ADD CONSTRAINT MOVIE_HAS_GENRE_GENRE_FK FOREIGN KEY 
    ( 
     GENRE_Genre_id
    ) 
    REFERENCES GENRE 
    ( 
     Genre_id
    ) 
;

ALTER TABLE MOVIE_HAS_GENRE 
    ADD CONSTRAINT MOVIE_HAS_GENRE_MOVIE_FK FOREIGN KEY 
    ( 
     MOVIE_Title_id
    ) 
    REFERENCES MOVIE 
    ( 
     Title_id
    ) 
;

ALTER TABLE RATING 
    ADD CONSTRAINT RATING_ACCOUNT_FK FOREIGN KEY 
    ( 
     ACCOUNT_Email_id
    ) 
    REFERENCES ACCOUNT 
    ( 
     Email_id
    ) 
;

ALTER TABLE RATING 
    ADD CONSTRAINT RATING_MOVIE_FK FOREIGN KEY 
    ( 
     MOVIE_Title_id
    ) 
    REFERENCES MOVIE 
    ( 
     Title_id
    ) 
;

ALTER TABLE VERSION 
    ADD CONSTRAINT VERSION_MOVIE_FK FOREIGN KEY 
    ( 
     MOVIE_Title_id
    ) 
    REFERENCES MOVIE 
    ( 
     Title_id
    ) 
;

ALTER TABLE VIEWER_FAVORS_MOVIE 
    ADD CONSTRAINT VIEWER_FAVORS_MOVIE_ACCOUNT_FK FOREIGN KEY 
    ( 
     ACCOUNT_Email_id
    ) 
    REFERENCES ACCOUNT 
    ( 
     Email_id
    ) 
;

ALTER TABLE VIEWER_FAVORS_MOVIE 
    ADD CONSTRAINT VIEWER_FAVORS_MOVIE_MOVIE_FK FOREIGN KEY 
    ( 
     MOVIE_Title_id
    ) 
    REFERENCES MOVIE 
    ( 
     Title_id
    ) 
;

ALTER TABLE VIEWER_WATCH_MOVIE 
    ADD CONSTRAINT VIEWER_WATCH_MOVIE_ACCOUNT_FK FOREIGN KEY 
    ( 
     ACCOUNT_Email_id
    ) 
    REFERENCES ACCOUNT 
    ( 
     Email_id
    ) 
;

ALTER TABLE VIEWER_WATCH_MOVIE 
    ADD CONSTRAINT VIEWER_WATCH_MOVIE_MOVIE_FK FOREIGN KEY 
    ( 
     MOVIE_Title_id
    ) 
    REFERENCES MOVIE 
    ( 
     Title_id
    ) 
;

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             24
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0